collections:
#     - name: ansible.tower
    - name: ibm.cloudcollection
    - name: azure.azcollection
#     - name: cisco.nxos
    - name: awx.awx
#    - name: jonnyfiveiq.test_collection
    - name: amazon.aws
    - name: google.cloud
#    - name: myfirst.test_collection
